config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
    # path('', TemplateView.as_view(template_name="home.html"))
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact-us/', views.contact_us, name='contact-us'),
    # path('contact-us/', views.ContactUsView.as_view(), name='contact-us'),
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging

logger = logging.getLogger(__name__)


class ContactUsForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(label='Your message',
                              max_length=100,
                              widget=forms.Textarea)

    def send_mail(self):
        logger.info('Sending mail to customer service')
        message = "From: {0}\n{1}".format(
            self.cleaned_data['name'],
            self.cleaned_data['message'])

        send_mail(
            subject="Site message",
            message=message,
            from_email="site@booktime.com",
            recipient_list=['customerservice@booktime.com'],
            fail_silently=False,
        )

main/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import FormView
from main import forms


def home(request):
    return render(request, 'main/home.html', {})


def about(request):
    return render(request, 'main/about.html', {})


def contact_us(request):
    if request.method == 'POST':
        form = forms.ContactUsForm(request.POST)
        if form.is_valid():
            form.send_mail()
            return redirect(reverse('main:home'))
    else:
        form = forms.ContactUsForm()
    return render(request, 'main/contact.html', {'form': form})


class ContactUsView(FormView):
    template_name = 'main/contact.html'
    form_class = forms.ContactUsForm
    success_url = '/'

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main/templates/main/_base.html
{% load compress %} {% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}" />
    {% endcompress %}
  </head>

  <body class="max-w-5xl mx-auto">
    {% include 'navbar.html' %}

    <div class="w-full">{% block content %} {% endblock content %}</div>

    <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
  </body>
</html>

main/templates/main/about.html
{% extends 'main/_base.html' %} {% block title %} About Page {% endblock title%}
{% block content %}
<h1
  class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white"
>
  About Page
</h1>
<p
  class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"
>
  Here at Flowbite we focus on markets where technology, innovation, and capital
  can unlock long-term value and drive economic growth.
</p>
{% endblock content %}

main/templates/main/contact.html
{% extends 'main/_base.html' %} {% block title %} Contact Us Page {% endblock %}
{% block content %}
<section
  class="bg-white dark:bg-gray-900 mx-5 mt-1 lg:mx-auto lg:max-w-xl flex flex-col space-y-3 items-center"
>
  <div class="py-8 lg:py-6 px-4 mx-auto w-full">
    <h2
      class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white"
    >
      Contact Us
    </h2>
    <p
      class="mb-8 lg:mb-10 font-light text-left text-gray-500 dark:text-gray-400 sm:text-xl"
    >
      Got a technical issue? Want to send feedback about a beta feature? Need
      details about our Business plan? Let us know.
    </p>
    <form method="POST" class="space-y-3">
      {% csrf_token %}
      <div>
        <label
          for="subject"
          class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"
          >{{form.name.label}}</label
        >
        <input
          type="text"
          id="id_name"
          name="name"
          value="{{form.name.value | default:""}}"
          class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
          placeholder="Let us know your name"
          required
        />
      </div>

      <div class="sm:col-span-2">
        <label
          for="message"
          class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400"
          >{{form.message.label}}</label
        >
         <textarea
          rows="6"
          id="id_message"
          name="message"
          value="{{form.message.value | default:""}}"
          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
          placeholder="Leave a message..."
        ></textarea>
      </div>
      <p>{{form.name.errors}}</p>
      <p>{{form.message.errors}}</p>
      <input
        type="submit"
        class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-blue-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
        value="Submit"
      />
    </form>
  </div>
</section>

{% endblock content %}

main/templates/main/home.html
{% extends 'main/_base.html' %} {% block title %} Home Page {% endblock title %}
{% block content %}

<p
  class="mb-6 text-lg font-normal text-gray-500 lg:text-xl sm:px-16 xl:px-48 dark:text-gray-400"
>
  Here at Flowbite we focus on markets where technology, innovation, and capital
  can unlock long-term value and drive economic growth.
</p>
{% endblock content %}

templates/navbar.html
<nav
  class="bg-white px-2 sm:px-4 py-2.5 dark:bg-gray-900 w-full border-b border-gray-200 dark:border-gray-600 mx-auto"
>
  <div class="container flex flex-wrap justify-between items-center w-full">
    <a href="https://flowbite.com/" class="flex items-center">
      <img
        src="https://flowbite.com/docs/images/logo.svg"
        class="mr-3 h-6 sm:h-9"
        alt="Flowbite Logo"
      />
      <span
        class="self-center text-xl font-semibold whitespace-nowrap dark:text-white"
        >Book Time</span
      >
    </a>
    <div class="flex md:order-2">
      <button
        type="button"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      >
        Get started
      </button>
      <button
        data-collapse-toggle="navbar-sticky"
        type="button"
        class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="navbar-sticky"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg
          class="w-6 h-6"
          aria-hidden="true"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>
    <div
      class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1"
      id="navbar-sticky"
    >
      <ul
        class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
      >
        <li>
          <a
            href="{% url 'main:home' %}"
            class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
            aria-current="page"
            >Home</a
          >
        </li>
        <li>
          <a
            href="{% url 'main:about' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >About</a
          >
        </li>

        <li>
          <a
            href="{% url 'main:contact-us' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Contact Us</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>